### ISSUE TITLE
Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket (RealWorldWeb.Router)

### ISSUE THREAD

**Issue by sravinet** [gothinkster/elixir-phoenix-realworld-example-app#23]
elixir -v
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.6.6 (compiled with OTP 20)

after follow-ing readme instructions & ensuring that there is no other elixir process running:

mix phx.server

[info] GET /phoenix/live_reload/socket/websocket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket (RealWorldWeb.Router)
    (real_world) lib/real_world_web/router.ex:1: RealWorldWeb.Router.__match_route__/4
    (real_world) lib/phoenix/router.ex:303: RealWorldWeb.Router.call/2
    (real_world) lib/real_world_web/endpoint.ex:1: RealWorldWeb.Endpoint.plug_builder_call/2
    (real_world) lib/plug/debugger.ex:102: RealWorldWeb.Endpoint."call (overridable 3)"/2
    (real_world) lib/real_world_web/endpoint.ex:1: RealWorldWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/sylvan/elixir-phoenix-realworld-example-app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

Please note that mix test run with no issue.

**Comment by victorbordo** [comment]
You might have figured this out already @sravinet but this is due to a misunderstanding of how the repo is supposed to be used. I was initially unaware of the complimentary frontend repo's intended to hook up to this service. The err above will be thrown while looking for a default index route that is not meant to exist. The issue should be closed.

**Comment by lbighetti** [comment]
Hi @sravinet !
Sorry for the delay.

@victorbordo explanation is correct, this error is correct, because this route is not supposed to exist.
Perhaps a better explanation in the README would be welcome clarifying the usage of this repo - You are not the first one to be confused by the actual intent of the repo.

I will think about how to improve this - suggestions are welcome of course!

I will close this but feel free to open a new issue if you have any further questions or issues.

**Comment by lbighetti** [comment]
and thanks for jumping in @victorbordo ! 👍 
I will take a look at the failing test!
